name: GitHub Actions
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      pictionaryKey: ${{ secrets.PICTIONARY_API_KEY }}
      translationKey: ${{ secrets.TRANSLATION_API_KEY }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: |
          chmod +x gradlew
          touch local.properties

#      - name: Detekt - check the code style
#        run: ./gradlew detekt
#      - name: Run all unit tests
#        run: ./gradlew testDebugUnitTest
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Archive outputs
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            app/build/intermediates/apk/debug/app-debug.apk
